name: internationalization_app
description: Flutter Internationalization

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.12+2
  provider: ^4.3.2+2
  pedantic: ^1.9.2
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FF000000"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - i18n/
    - assets/